Auth grant type jwt bearer tests
TinkoffCreditSystems/fosite pull request #1
Opened 2020-12-09 16:39 UTC by seliverstov-tinkoff

## Related issue

## Proposed changes

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation within the code base (if appropriate).

## Further comments

2020-12-09 17:03 UTC, Xopek reviewed
Сами тесты завтра гляну

2020-12-09 17:03 UTC, Xopek commented on integration/helper_setup_test.go
> +const secondJWTBearerIssuer = "second@tinkoff.ru"
Это opensource все же, давай тут что-то более нейтральное, example.com например

2020-12-09 17:03 UTC, Xopek commented on integration/helper_setup_test.go
> +								"vk.com",
vk.com я бы тоже убрал :)

2020-12-09 17:03 UTC, Xopek commented on integration/helper_setup_test.go
> +		TokenURL: ts.URL + "/token",
"/token" может тоже в константу? Чтобы можно в другом месте reference на нее сделать, например там, где мы будем поднимать сервер

2020-12-09 17:03 UTC, Xopek commented on integration/clients/introspect.go
> +type IntrospectForm struct {
А что такое форма?

2020-12-09 17:03 UTC, Xopek commented on integration/clients/introspect.go
> +func NewIntrospectClient(url string) *Introspect {
предложил бы для понятности назвать endpointURL

2020-12-09 17:03 UTC, Xopek commented on integration/clients/jwt_bearer.go
> +type JWTBearerConfig struct {
а нужна нам тут структура ради одного поля? может прям это поле и запихать?

2020-12-09 17:03 UTC, Xopek commented on integration/clients/jwt_bearer.go
> +func (c *JWTBearer) getAssertion(payloadData *JWTBearerPayload) ([]byte, error) {
а зачем мы руками assertion собираем, когда есть либа jose, которая в fosite испоьзуется. А умеет jwt генерить и структуры данных у нее есть уже.

2020-12-09 17:55 UTC, seliverstov-tinkoff commented on integration/clients/introspect.go
> +type IntrospectForm struct {
тип данных application/x-www-form-urlencoded

т.е мы передаем закодированную форму

2020-12-09 18:28 UTC, seliverstov-tinkoff commented on integration/helper_setup_test.go
> +const secondJWTBearerIssuer = "second@tinkoff.ru"
done

2020-12-09 18:28 UTC, seliverstov-tinkoff commented on integration/helper_setup_test.go
> +								"vk.com",
done

2020-12-09 18:28 UTC, seliverstov-tinkoff commented on integration/helper_setup_test.go
> +		TokenURL: ts.URL + "/token",
done

2020-12-09 18:28 UTC, seliverstov-tinkoff commented on integration/clients/introspect.go
> +func NewIntrospectClient(url string) *Introspect {
done

2020-12-09 18:28 UTC, seliverstov-tinkoff commented on integration/clients/jwt_bearer.go
> +type JWTBearerConfig struct {
done

2020-12-09 18:30 UTC, seliverstov-tinkoff commented on integration/clients/jwt_bearer.go
> +func (c *JWTBearer) getAssertion(payloadData *JWTBearerPayload) ([]byte, error) {
Кажется он не умеет kid в заголовок записывать или я не разобрался.
насколько тебе кажется это критичным?

2020-12-09 18:30 UTC, seliverstov-tinkoff commented on integration/clients/jwt_bearer.go
> +func (c *JWTBearer) getAssertion(payloadData *JWTBearerPayload) ([]byte, error) {
Кажется он не умеет kid в заголовок записывать или я не разобрался.

насколько тебе кажется это критичным?

2020-12-10 07:32 UTC, Xopek commented on integration/clients/jwt_bearer.go
> +func (c *JWTBearer) getAssertion(payloadData *JWTBearerPayload) ([]byte, error) {
Он уммет
`jwk := jose.JSONWebKey{Key: s.privateKey, KeyID: keyID, Algorithm: string(jose.RS256)}
	sig, err := jose.NewSigner(jose.SigningKey{Algorithm: jose.RS256, Key: jwk}, (&jose.SignerOptions{}).WithType("JWT"))`

Мне кажется довольно критичным, учитывая что мы тестим тут вещь, которая напрямую связана с безопасностью, лучше по максимуму использовать готовые проверенные решения, а не писать свои. Ну это мое мнение.

2020-12-10 10:22 UTC, Xopek requested changes

2020-12-10 10:22 UTC, Xopek commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) assertSuccessResponse(t *testing.T, token *clients.Token, err error) {
лучше такие вспомогатильные методы вниз теста уносить, все таки в тесте первое, что хочется видеть это тесты. Исключение только - сетап тестов, так как это довольно важно и помогает понять, что будет происходить на мой взгляд.

2020-12-10 10:22 UTC, Xopek commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) TestBaseConfiguredClient() {
из названия кажется, что мы тестируем некий базовый сконфигурированный клиент, хотя по факту мы тут  тестируем просто success сценарий? Типо нормальные параметры передал, получил нормальный ответ. Нормально делай нормально будет аля ))

2020-12-10 10:22 UTC, Xopek commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) TestListOfAudience() {
опять же, я бы предложил более говорящие названия, чтобы читалось как сценарий теста: TestSuccessResponseWithMultipleAudenceInAssertion

2020-12-10 10:22 UTC, Xopek commented on integration/authorize_jwt_bearer_test.go
> +		Audience: []string{"https://www.ory.sh/api", "https://vk.com/oauth"},
давай vk заменим на example.com

2020-12-10 10:22 UTC, Xopek commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) TestFewScopes() {
Аналогично TestSuccessResponseWithMultipleScopesInRequest

2020-12-10 10:22 UTC, Xopek commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) TestGetTokenWithRandomClaim() {
звучит так, что не должно проходить) Может в сторону ExtraClaim?

2020-12-10 10:22 UTC, Xopek commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) TestMaxDuration() {
TestAssertionWithLongDurationWillFail - ну опять же, чтобы было понятно, что тестируем и читалось хорошо. Вариант мой тоже примерный, если у тебя есть получше вариант, я только за)

2020-12-10 10:22 UTC, Xopek commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) TestDuplicatedJTI() {
Тут лучше написать в духе: "повторный запрос с тем же JTI должен падать". И стоит добавить success сценарий, когда ты делаешь запрос, ждешь время равное exp и делаешь повторный запрос и он должен пройти.

2020-12-10 10:22 UTC, Xopek commented on integration/authorize_jwt_bearer_test.go
> +		Subject:  "",
тест говорит, что не должно быть issuer, а тут subject пропущен

2020-12-10 10:22 UTC, Xopek commented on integration/authorize_jwt_bearer_test.go
> +		Subject:  secondJWTBearerIssuer,
немножко путает, что ты сюда issuer прописываешь, я бы предложил "wrong_subject" сюда просто записать

2020-12-10 10:22 UTC, Xopek commented on integration/authorize_jwt_bearer_test.go
> +		Issuer:   secondJWTBearerIssuer,
вот тут непонятно почему тест падает, то ли ты неправильно issuer задал, то ли неправильно subject просто указал. Я бы предложил сделать как-то более выразительно. Типо "not_existing_issuer".

2020-12-10 10:22 UTC, Xopek commented on integration/authorize_jwt_bearer_test.go
> +	}, []string{"fosite", "lenovo"})
я все же за то, чтобы в тестах были данные похожие на жизнь. Вряд ли в жизни будет scope lenovo, скорее уж какой-нибудь permission.

2020-12-10 10:22 UTC, Xopek commented on integration/authorize_jwt_bearer_test.go
> +			TokenURL:              "https://www.ory.sh/api",
я бы в константу вынес, чтобы одно и тое значение было и в запросе и при поднятии сервера

2020-12-10 10:22 UTC, Xopek commented on integration/authorize_jwt_bearer_required_iat_test.go
> +type authorizeJWTBearerRequiredAITSuite struct {
а ты не хочешь этот suite занести в тот же файл authorize_jwt_bearer_test? Ну типо чтобы все тесты на jwt_bearer в одном файле лежали. Ну это так, сам до конца в этом не уверен, стоит ли так делат ))

2020-12-10 10:22 UTC, Xopek commented on integration/authorize_jwt_bearer_required_iat_test.go
> +func (s *authorizeJWTBearerRequiredAITSuite) TestBaseConfiguredClient() {
писал уже про название

2020-12-10 10:22 UTC, Xopek commented on integration/authorize_jwt_bearer_required_iat_test.go
> +type authorizeJWTBearerRequiredAITSuite struct {
authorizeJWTBearerRequiredAITSuite - название кстати неправильное, не AIT, а IAT

2020-12-10 10:22 UTC, Xopek commented on integration/authorize_jwt_bearer_required_jti_test.go
> +func (s *authorizeJWTBearerRequiredJtiSuite) TestBaseConfiguredClient() {
название

2020-12-10 10:22 UTC, Xopek commented on integration/authorize_jwt_bearer_required_jti_test.go
> +	s.assertBadRequestResponse(s.T(), token, err)
Из содержимого теста не понятно, почему оно должно упасть

2020-12-10 10:22 UTC, Xopek commented on integration/authorize_jwt_bearer_required_iat_test.go
> +	s.assertBadRequestResponse(s.T(), token, err)
Из содержимого теста не понятно почему должны упасть. Для выразительности надо название поправить теста и прям в тесте делать обнуление IssuerAt например, чтобы видно было, что ты без него создаешь assertion

2020-12-10 10:22 UTC, Xopek commented on integration/introspect_jwt_bearer_token_test.go
> +func (s *introspectJwtBearerTokenSuite) assertSuccessResponse(
тоже бы внес унес вспомогательные функции, после тестов, чтоб были

2020-12-10 10:22 UTC, Xopek commented on integration/introspect_jwt_bearer_token_test.go
> +	token2, _ := s.getAPPJWTClient().GetToken(ctx, s.appTokenPayload, s.scopes)
не понятно что это за токены такие, чем второй от первого отличается. Это assertion токены или это токены для авторизации? Я так понял один assertion, другой авторизационный

2020-12-10 10:22 UTC, Xopek commented on integration/introspect_jwt_bearer_token_test.go
> +	assert.Equal(t, response.Subject, firstJWTBearerSubject)
это очень неявно, почему мы во всех тестах считаем, что должен быть именно firstJWTBearerSubject? Лучше все это в параметры уносить.

2020-12-10 10:22 UTC, Xopek commented on integration/introspect_jwt_bearer_token_test.go
> +func (s *introspectJwtBearerTokenSuite) TestIntrospectByYourself() {
А что значит by yourself?

2020-12-10 17:14 UTC, seliverstov-tinkoff commented on integration/clients/jwt_bearer.go
> +func (c *JWTBearer) getAssertion(payloadData *JWTBearerPayload) ([]byte, error) {
done

2020-12-10 17:54 UTC, seliverstov-tinkoff commented on integration/introspect_jwt_bearer_token_test.go
> +	token2, _ := s.getAPPJWTClient().GetToken(ctx, s.appTokenPayload, s.scopes)
один проверяется от лица второго, если токен хочет проверить сам себя - ошибка

2020-12-10 18:00 UTC, seliverstov-tinkoff commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) assertSuccessResponse(t *testing.T, token *clients.Token, err error) {
done

2020-12-10 18:00 UTC, seliverstov-tinkoff commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) TestBaseConfiguredClient() {
done

2020-12-10 18:01 UTC, seliverstov-tinkoff commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) TestListOfAudience() {
done

2020-12-10 18:01 UTC, seliverstov-tinkoff commented on integration/authorize_jwt_bearer_test.go
> +		Audience: []string{"https://www.ory.sh/api", "https://vk.com/oauth"},
done

2020-12-10 18:03 UTC, seliverstov-tinkoff commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) TestFewScopes() {
done

2020-12-10 18:03 UTC, seliverstov-tinkoff commented on integration/authorize_jwt_bearer_required_iat_test.go
> +	s.assertBadRequestResponse(s.T(), token, err)
done

2020-12-10 18:03 UTC, seliverstov-tinkoff commented on integration/introspect_jwt_bearer_token_test.go
> +func (s *introspectJwtBearerTokenSuite) assertSuccessResponse(
done

2020-12-10 18:04 UTC, seliverstov-tinkoff commented on integration/introspect_jwt_bearer_token_test.go
> +	assert.Equal(t, response.Subject, firstJWTBearerSubject)
done

2020-12-10 18:04 UTC, seliverstov-tinkoff commented on integration/introspect_jwt_bearer_token_test.go
> +func (s *introspectJwtBearerTokenSuite) TestIntrospectByYourself() {
done

2020-12-11 08:36 UTC, Xopek requested changes

2020-12-11 08:36 UTC, Xopek commented on integration/authorize_jwt_bearer_required_iat_test.go
> +func (s *authorizeJWTBearerRequiredAITSuite) TestBadResponseWithoutIssuedAt() {
опечатку в названии Suit'а так и не поправил

2020-12-11 08:36 UTC, Xopek commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) TestSuccessResponseWithRandomClaim() {
на extra не захотел менять?

2020-12-11 08:36 UTC, Xopek commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) TestBadResponseWithInvalidPrivatKey() {
опечатка, private

2020-12-11 08:36 UTC, Xopek commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) TestBadResponseWithDuplicatedJTI() {
duplicated как я уже писал ранее не отображает смысл происходящего, у нас же не JTI задублирован дважды в запросе, а повторные запросы не должны проходит на определенное время

2020-12-11 08:36 UTC, Xopek commented on integration/clients/jwt_bearer.go
> +	PrivateKey jose.Signer
это подпись теперь, а не приватный ключ

2020-12-11 08:36 UTC, Xopek commented on integration/introspect_jwt_bearer_token_test.go
> +func (s *introspectJwtBearerTokenSuite) TestSuccessResponseWithMultipleScopesToken() {
я все еще не понимаю этот тест. Почему в нем участвует два разных каких-то клиента? И почему два разных токена?

2020-12-11 09:01 UTC, Xopek commented on integration/introspect_jwt_bearer_token_test.go
> +	token2, _ := s.getAPPJWTClient().GetToken(ctx, s.appTokenPayload, s.scopes)
А что значит один проверяет от лица другого? Такого понятия нет, ты просто имеешь на руках токен и идешь в ручку, чтобы сделать для него детализацию и все.

И зачем здесь нужна авторизация в header'ах? Без нее не даст интроспект сделать? Если даже она нужна, то client никак не связан с токеном, который он интроспектит в fosite. В гидре точно можно без аутентификации клиента делать интроспект.

2020-12-11 09:52 UTC, egdeliya commented on integration/helper_setup_test.go
> +		secondJWTBearerIssuer: {
[необязательно]

выглядит как огромная helper функция, которая параметризуется `Issuer`, `privateKey`, `keyID`, `scopes`, возвращает storage.IssuerPublicKeys для определенного issuer

2020-12-11 15:33 UTC, seliverstov-tinkoff commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) TestGetTokenWithRandomClaim() {
поменял на RandomClaim -> ExtraClaim, ты же о этом пишешь, а то не ясно)

2020-12-11 15:34 UTC, seliverstov-tinkoff commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) TestDuplicatedJTI() {
теперь TestBadResponseForSecondRequestWithSameJTI

2020-12-11 15:35 UTC, seliverstov-tinkoff commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) TestDuplicatedJTI() {
+ добавил тест когда с тем же jti но прошлый запрос уже протух

2020-12-11 15:35 UTC, seliverstov-tinkoff commented on integration/authorize_jwt_bearer_test.go
> +		Subject:  "",
done

2020-12-11 15:35 UTC, seliverstov-tinkoff commented on integration/authorize_jwt_bearer_test.go
> +		Subject:  secondJWTBearerIssuer,
done

2020-12-11 15:36 UTC, seliverstov-tinkoff commented on integration/authorize_jwt_bearer_test.go
> +		Issuer:   secondJWTBearerIssuer,
done +-

2020-12-11 15:36 UTC, seliverstov-tinkoff commented on integration/authorize_jwt_bearer_test.go
> +	}, []string{"fosite", "lenovo"})
done

2020-12-11 15:39 UTC, seliverstov-tinkoff commented on integration/authorize_jwt_bearer_required_iat_test.go
> +type authorizeJWTBearerRequiredAITSuite struct {
не хочу, каждый файл имеет свой один test suit, мне не нравится положение дел, когда много сложных структур в одном файле, если разговор про количество файлов в пакете, то я бы разбивал на под пакеты по стратегиям авторизации/аутентификации, однако, мне кажется подобные решение я принимать не могу.

AIT - done

2020-12-11 15:40 UTC, seliverstov-tinkoff commented on integration/introspect_jwt_bearer_token_test.go
> +	token2, _ := s.getAPPJWTClient().GetToken(ctx, s.appTokenPayload, s.scopes)
На созвоне договорились создавать хедер на этапе инициализации, а не в каждом тесте

2020-12-11 15:40 UTC, seliverstov-tinkoff commented on integration/authorize_jwt_bearer_required_iat_test.go
> +func (s *authorizeJWTBearerRequiredAITSuite) TestBadResponseWithoutIssuedAt() {
done

2020-12-11 15:40 UTC, seliverstov-tinkoff commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) TestSuccessResponseWithRandomClaim() {
done

2020-12-11 15:41 UTC, seliverstov-tinkoff commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) TestBadResponseWithInvalidPrivatKey() {
done

2020-12-11 15:41 UTC, seliverstov-tinkoff commented on integration/authorize_jwt_bearer_test.go
> +func (s *authorizeJWTBearerSuite) TestBadResponseWithDuplicatedJTI() {
done

2020-12-11 15:41 UTC, seliverstov-tinkoff commented on integration/clients/jwt_bearer.go
> +	PrivateKey jose.Signer
done

2020-12-11 15:42 UTC, seliverstov-tinkoff commented on integration/introspect_jwt_bearer_token_test.go
> +func (s *introspectJwtBearerTokenSuite) TestSuccessResponseWithMultipleScopesToken() {
как я понял это продолжения этого треда, верно?

https://github.com/TinkoffCreditSystems/fosite/pull/1#discussion_r540046599

2020-12-11 15:42 UTC, seliverstov-tinkoff commented on integration/helper_setup_test.go
> +		secondJWTBearerIssuer: {
done

2020-12-11 16:15 UTC, egdeliya commented on integration/introspect_jwt_bearer_token_test.go
> +	assert.NotEmpty(s.T(), response.Scope, scopes)
тут скорее всего на `Equal` проверка должна была быть

2020-12-11 17:38 UTC, egdeliya commented on integration/introspect_jwt_bearer_token_test.go
> +func (s *introspectJwtBearerTokenSuite) TestSuccessResponseWithMultipleScopesToken() {
видимо нельзя сделать интроспект без авторизации в этих тестах

мейнтейнеры по крайней мере это делают - https://github.com/TinkoffCreditSystems/fosite/blob/master/integration/introspect_token_test.go#L84

и тест на то, что introspect не проходит не с тем авторизац хедером тоже есть у них - https://github.com/TinkoffCreditSystems/fosite/blob/master/integration/introspect_token_test.go#L112

2020-12-11 17:41 UTC, egdeliya reviewed
Выглядит очень хорошо :) проверки по всем фронтам, с разными параметрами, прямо здорово

Нужно разобраться только с этой историей про авторизацию в `introspect`

2020-12-11 20:27 UTC, seliverstov-tinkoff commented on integration/introspect_jwt_bearer_token_test.go
> +	assert.NotEmpty(s.T(), response.Scope, scopes)
done

2020-12-14 09:13 UTC, egdeliya approved these changes

2020-12-14 09:42 UTC, Xopek approved these changes

2020-12-14 09:49 UTC, merged